/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS-PC
 */
public class KonversiSuhu extends javax.swing.JFrame {
    double celcius;
    double fahrenheit;
    double reamur;
    double kelvin;

    public KonversiSuhu() {
        initComponents();
    }
    
    private void Celcius() {
        celcius = Double.parseDouble(SuhuAwal.getText());
        
        fahrenheit =celcius * 1.8 +32;
        reamur = celcius * 0.8;
        kelvin =celcius + 273.15;
        lblCelcius.setText(celcius+ "Celcius");
        lblFahrenheit.setText(fahrenheit+ " Fahrenheit");
        lblReamur.setText(reamur+ "Reamur");
        lblKelvin.setText(kelvin+ "Kelvin");
    }
    
    private void Fahrenheit() {
        fahrenheit = Double.parseDouble(SuhuAwal.getText());
        
        celcius =(fahrenheit - 32) / 1.8;
        reamur = (fahrenheit - 32) / 2.25;
        kelvin =(fahrenheit + 459.67) / 1.8;
        lblCelcius.setText(celcius+ "Celcius");
        lblFahrenheit.setText(fahrenheit+ " Fahrenheit");
        lblReamur.setText(reamur+ "Reamur");
        lblKelvin.setText(kelvin+ "Kelvin");
    }
    
    private void Reamur() {
        reamur = Double.parseDouble(SuhuAwal.getText());
        
        celcius =reamur/ 0.8;
        fahrenheit =(reamur * 2.25)+32;
        kelvin =(reamur / 0.8) + 273.15;
        lblCelcius.setText(celcius+ "Celcius");
        lblFahrenheit.setText(fahrenheit+ " Fahrenheit");
        lblReamur.setText(reamur+ "Reamur");
        lblKelvin.setText(kelvin+ "Kelvin");
    }
    
    private void Kelvin() {
        kelvin = Double.parseDouble(SuhuAwal.getText());
        
        celcius =kelvin - 273.15;
        fahrenheit =kelvin * 1.8 - 459.67;
        reamur =(kelvin - 273.15) * 0.8;
        lblCelcius.setText(celcius+ "Celcius");
        lblFahrenheit.setText(fahrenheit+ " Fahrenheit");
        lblReamur.setText(reamur+ "Reamur");
        lblKelvin.setText(kelvin+ "Kelvin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SuhuAwal = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        celciusLabel = new javax.swing.JLabel();
        lblFahrenheit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        lblCelcius = new javax.swing.JLabel();
        lblReamur = new javax.swing.JLabel();
        lblKelvin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)), "Celcius To Fahrenheit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SuhuAwal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(SuhuAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, -1));

        btnConvert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 143, -1));

        celciusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        celciusLabel.setText("Suhu Awal");
        jPanel1.add(celciusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 81, -1));

        lblFahrenheit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFahrenheit.setText("Fahrenheit");
        jPanel1.add(lblFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        rbCelcius.setText("Celcius");
        jPanel1.add(rbCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        rbFahrenheit.setText("Fahrenheit");
        jPanel1.add(rbFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        rbReamur.setText("Reamur");
        jPanel1.add(rbReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        rbKelvin.setText("Kelvin");
        jPanel1.add(rbKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        lblCelcius.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCelcius.setText("Celcius");
        jPanel1.add(lblCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        lblReamur.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReamur.setText("Reamur");
        jPanel1.add(lblReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, -1));

        lblKelvin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKelvin.setText("Kelvin");
        jPanel1.add(lblKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        if (rbCelcius.isSelected()){
            Celcius();
        }else if (rbFahrenheit.isSelected()){
            Fahrenheit();
        }else if (rbReamur.isSelected()){
            Reamur();
        }else if (rbKelvin.isSelected()){
            Kelvin();
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        SuhuAwal.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SuhuAwal;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel celciusLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelcius;
    private javax.swing.JLabel lblFahrenheit;
    private javax.swing.JLabel lblKelvin;
    private javax.swing.JLabel lblReamur;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    // End of variables declaration//GEN-END:variables
}
